version: '3.9'

services:
  web-service:
    build: 
      context: .
      dockerfile: Dockerfile
    image: could-based-app-hw1-local
    ports:
      - "8080:8080"
    container_name: could-based-app-hw1-local