version: '3.9'

services:
  web-service:
    build: 
      context: .
      dockerfile: Dockerfile
    image: web-application-app
    ports:
      - "8080:8080"
    container_name: web-application-app