apiVersion: v1
kind: Service
metadata:
  name: cloud-based-hw1-service
spec:
  type: NodePort
  selector:
    app: cloud-based-hw1
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080